services:
  nodo-a:
    build: ./nodoA
    ports:
      - "2000:2000"
    container_name: nodo-a

  nodo-b:
    build: ./nodoB
    ports:
      - "3000:3000"
    depends_on:
      - nodo-a
    container_name: nodo-b

  nodo-c:
    build: ./nodoC
    ports:
      - "4000:4000"
    depends_on:
      - nodo-b
    container_name: nodo-c
