version: '3.8'
services:
  nodoA:
    build: ./nodoA
    ports:
      - "2000:2000"

  nodoB:
    build: ./nodoB
    ports:
      - "3000:3000"
    depends_on:
      - nodoA
  nodoC:
    build: ./nodoC
    ports:
      - "4000:4000"
    depends_on:
      - nodoB
